<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!--<link href="http://fonts.googleapis.com/css?family=Raleway:600,400,300" rel="stylesheet" type="text/css" media="all">-->
        <!--<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" media="all">-->
        <link rel="stylesheet/less" href="<?=$this->basePath()?>/css/style.less">
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/animate.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
         ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/less.js')
        	->prependFile($this->basePath() . '/js/global.js')
        	->prependFile($this->basePath() . '/js/jquery.mask.js')
        	->prependFile($this->basePath() . '/js/plugin/modal.js')
            //->prependFile($this->basePath() . '/js/plugin/jquery.bootstrap.js')
            ->prependFile($this->basePath() . '/js/plugin/jquery.tooltip.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
      
    </head>
    <body>
    	
		<!-- -->
		<div class="div-total-topo transition-all">
			<div class="navbar">
				<div class="div-limiter">
					<div class="navbar-logo">
					    <a href="<?=$this->basePath()?>/">Social<span>Uno</span></a>	
					</div>
					<div class="navbar-options">
						<ul>
							<?= $this->session()->offsetGet('user') ? '<li><a href="javascript:logout()"><span class="fa fa-power-off"></span></a></li>'  : ''?>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
		<!-- -->
		<div class="div-total-meio">
			<div class="container">			    
				
			    <?php echo $this->content; ?>
	
			</div>
		</div>
		
		<!-- -->
		<div class="div-total-rodape">
		    <div class="div-limiter">
		        <div class="footerbar-desc">
		         	<a href="<?=$this->basePath()?>/">SocialUno</a><br>
		         	<span>Todos os direitos reservados &copy;</span>
		        </div>
		    </div>
		</div>
		
		<div class="div-notificador">
			<div class="div-descricao">
				<div class="div-balao grande div-box"></div>
				<div class="div-balao pequeno div-box"></div>
				<div class="div-conteudo div-box">Nova solicitação de amizade.</div>
			</div>
			<div class="div-img div-box"><img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1/v/t1.0-1/p50x50/21801_750831558369521_6358608693887282028_n.jpg?oh=59902f082ab6be3525cc9f50aa67ba70&amp;oe=560D90F7&amp;__gda__=1442134310_41a80f4f30ff030caaae942925cbb232"></div>
		</div>	

		<!-- -->
		<div id="modal-foto-perfil" class="div-modal-fundo transition-all">
			<div class="div-conteudo-modal div-box modal-foto-perfil">
				
				<!-- -->
				<form>
				
					<input type="file">
				
				</form>
				
			</div>			
		</div>	
		
		<?php echo $this->inlineScript() ?>
        
    </body>
</html>
