<?php
	
	$quantidade = count($usuarios);
	foreach($usuarios as $list) {
		?>
			<div class="usuarios-busca" id="usuario_<?=$list['id']?>"> 
				<a href="/social-uno/friend-profile/index?user=<?=$list['id']?>">
					<div class="nome-usuario"><?=$list['nome_exibicao']?></div>        
					<div class="img-facebook"><img src="<?=$list['caminho']?>"></div>
				</a>
			</div>
		<?php 
	}
	if($quantidade == 0) {
		?>
			<div class="usuarios-busca erro"> 
				<div class="erro-usuario">Nenhum resultado encontrado.</div>        
			</div>
		<?php 
	}	
?>