<!-- -->
<div class="div-box-public div-box transition-all">

	<form id="" class="" name="" action="" method="" enctype="multipart/form-data">
	
		<!-- -->
		<div class="form-box">	
			<textarea id="" class="form-group" placeholder="Compartilhe algo com os seus amigos..."></textarea>
		</div>
		
		<!-- -->
		<div class="form-box text-align-right">
			<div class="div-input-select-publicacao" data-toggle="tooltip" data-placement="bottom" title="Quem poderá ver essa publicação?">
				<select>
					<option><i class="fa fa-user"></i> Somente eu</option>
					<option>Amigos</option>
					<option>Todos</option>
				</select>
			</div>
			<button id="" class="btn principal" type="button" data-toggle="tooltip" data-placement="bottom" title="Adicionar fotos"><i class="fa fa-camera"></i></button>
			<button id="" class="btn principal" type="button" data-toggle="tooltip" data-placement="bottom" title="Adicionar pessoas"><i class="fa fa-user-plus"></i></button>
			<button id="" class="btn principal" type="button">Publicar</button>
		</div>			
		
	</form>

</div>

<!-- -->
<div class="div-box-ind-public">
	
	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>

	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>
	
	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>
				
</div>