<!-- -->
<div class="div-box-public div-box transition-all">

	<form id="form-publicacao" class="" name="" action="" method="POST" enctype="multipart/form-data">
	
		<!-- -->
		<div class="form-box">	
			<textarea id="text-area-publicacao" name="text-area-publicacao" class="form-group" placeholder="Compartilhe algo com os seus amigos..."></textarea>
		</div>
		<div class="hide">
			<input type="file" name="fotosLinhaTempo[]" id="fotosLinhaTempo" multiple>
		</div>
		<!-- -->
		<div class="form-box text-align-right">
			<div class="quantidade-imagens">

			</div>

			<div class="div-input-select-publicacao" data-toggle="tooltip" data-placement="bottom" title="Quem poderá ver essa publicação?">
				<select name="permissao">
					<option value="1" selected="" ></i> Somente eu</option>
					<option value="2">Amigos</option>
					<option value="3">Todos</option>
				</select>
			</div> 
			<label id="" class="btn principal icon-camera" type="button" data-toggle="tooltip" data-placement="bottom" title="Adicionar fotos" for="fotosLinhaTempo"><i class="fa fa-camera icon-camera"></i></label>
			<button id="publicar-post" class="btn principal" type="submit">Publicar</button>
		</div>			
		
	</form>

</div>

<!-- -->
<div class="div-box-ind-public">
	
	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>

	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>
	
	<!-- -->
	<div class="div-box-ind-ind-public div-box">
	</div>
				
</div>


<?php 
echo $this->headScript()  
->prependFile($this->basePath() . '/js/index/index.js');

?>