<!-- -->
<div class="div-box-ind-ind-public-configuracoes div-box">

	
	<div class="div-form-cadastro transition-all">

	    <h3 class="titulo-box">Configurações <?=$usuario->getNome_exibicao()?></h3>
		
		<input type="hidden" id="id_user" value="<?=$usuario->getId()?>">

		<!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-left">
	    	<label for="nome_usuario">Nome*:</label>
			<input type="text" id="nome_usuario" value="<?=$usuario->getNome()?>">
	    </div>

	    <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-right">
	    	<label for="sobrenome_usuario">Sobrenome*:</label>
			<input type="text" id="sobrenome_usuario" value="<?=$usuario->getSobrenome()?>">
	    </div>

	     <div class="form-box width-50 text-align-left zerar-padding-left">
	    	<label for="sexo">Sexo*:</label>
			<select id="sexo">
				<option <?=$usuario->getSexo() == 'M' ? 'selected' : ''?> value="M">Masculino</option>
				<option <?=$usuario->getSexo() == 'F' ? 'selected' : ''?> value="F">Feminino</option>
			</select>
	    </div>

	     <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-right">
	    	<label for="relacionamento">Status Relacionamento:</label>
			<input type="text" id="relacionamento" value="<?=$usuario->getRelacionamento()?>">
	    </div>

	    <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-left">
	    	<label for="profissao">Profissão:</label>
			<input type="text" id="profissao" value="<?=$usuario->getProfissao()?>">
	    </div>

	    <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-right">
	    	<label for="formacao">Formação:</label>
			<input type="text" id="formacao" value="<?=$usuario->getFormacao()?>">
	    </div>

	    <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-left">
	    	<label for="local_trabalho">Local de Trabalho:</label>
			<input type="text" id="local_trabalho" value="<?=$usuario->getLocalTrabalho()?>">
	    </div>

	     <!-- -->
	    <div class="form-box width-50 text-align-left zerar-padding-right">
	    	<label for="endereco">Endereço:</label>
			<input type="text" id="endereco" value="<?=$usuario->getEndereco()?>">
	    </div>
		<div class="form-box text-align-right">	
	   		 <button class="btn principal" onclick="saveDadosConfiguracoes()">Salvar</button>
	   	</div>

	</div>

</div>

<?php 
echo $this->headScript()  
->prependFile($this->basePath() . '/js/configuracoes/configuracoes.js');

?>